Version 1.2.18 - remove dependency of lame and faac before installing mp4live, added G.711 as a encoder and decoder, fixed some mp4v2 rounding, 64 bit compiling, h264 ctts creations, some general clean up

diff --git a/cvs_bootstrap b/cvs_bootstrap
--- a/cvs_bootstrap
+++ b/cvs_bootstrap
@@ -46,48 +46,33 @@ target_system=`uname -s`
       exit 1
    fi
 #
-# Test for lame
+# Test for faac
 #
 allargs="$@"
 
 if test $target_system = "Linux"; then
-
-    have_lame=no
-    if lame --version >/dev/null 2>/dev/null
-	then
-	lamever=`lame --version | tr '.' ' '`
-	lameresult=`util/testlame.sh $lamever`
-	if test $lameresult = "yes"; then
-	    have_lame=yes
-	fi
-    fi
+    have_faac=no
     if which faac >/dev/null 2>/dev/null; then
 	have_faac=yes
-    else
-	have_lame=no
     fi
 
-    if test $have_lame = "no"; then
-	disabled_mp4live=no
-	while test $# -gt 0;
-	  do
-	  if test $1 = "--disable-server"; then
-	      disabled_mp4live=yes
-	  else
-	      if test $1 = "--disable-mp4live"; then
-		  disabled_mp4live=yes
-	      fi
-	  fi
-	  shift
-	done
-	if test $disabled_mp4live = no; then
-	    echo "Error - we cannot detect a valid version of lame or faac and you are trying"
-	    echo "to build mpeg4ip with mp4live."
-	    echo "To remedy this, either reexecute this program with either the"
-	    echo "--disable-mp4live or --disable-server options -OR-"
-	    echo "install lame at version 3.92 or greater from http://www.mp3dev.org"
-	    echo "and libfaac at verion 1.20 or greater from http://www.audiocoding.com"
-	    exit 1
+    if test $have_faac = "yes"; then
+	# we have lame and faac - see if faac is built with mp4 support
+	faac --help >&faac_help
+	sdf=`grep "MP4 support unavailable" faac_help`
+	rm -f faac_help
+	if test -n $sdf; then
+	    if which mpeg4ip-config >/dev/null 2>/dev/null; then
+		echo "Warning - faac uses libmp4v, but we've detected a version"
+		echo "of mpeg4ip.  If you get errors building mp4live, please"
+		echo "rebuild faac without mp4v2 support"
+	    else
+		echo "Error - we have detected a version of faac that has libmp4v2 support"
+		echo "and no copy of mpeg4ip-config.  This means faac was built with"
+		echo "faad2 and the libraries will be incompatible".
+		echo "Please reinstall faac without mp4v2 support"
+		exit 1
+	    fi
 	fi
     fi
 fi
@@ -147,28 +132,13 @@ if `aclocal $ACLOCAL_FLAGS`; then
     ACLOCAL_FLAGS="-I $pwd/doc $ACLOCAL_FLAGS"
     aclocal $ACLOCAL_FLAGS
   fi
-  if grep AM_PATH_GTK aclocal.m4 | grep -v AM_PATH_GTK_2_0; then
-      echo
-  else 
-      ACLOCAL_FLAGS="-I $pwd/util $ACLOCAL_FLAGS"
-      aclocal $ACLOCAL_FLAGS
-  fi
 else
 if `aclocal -I $pwd/doc`; then
 ACLOCAL_FLAGS="-I $pwd/doc $ACLOCAL_FLAGS"
-else
-if `aclocal -I $pwd/util $ACLOCAL_FLAGS`; then
-ACLOCAL_FLAGS="-I $pwd/util $ACLOCAL_FLAGS"
-else
-if `aclocal -I $pwd/doc -I $pwd/util $ACLOCAL_FLAGS`; then
-ACLOCAL_FLAGS="-I $pwd/doc -I $pwd/util $ACLOCAL_FLAGS"
-fi
-fi
 fi
 fi
 
 libtoolize --force
-grep AM_PATH_GTK_2_0 aclocal.m4 || aclocal -I doc || exit 3
 autoheader || exit 1
 automake --add-missing --foreign || exit 1
 autoconf || exit 1
